name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build docker image for testing
        run: docker build -t my-app-test:latest .

      # Run tests with coverage
      - name: Run tests with coverage
        run: |
          docker run --name my_app_test_container --rm my-app-test:latest \
            sh -c "pytest --cov=. --cov-report=xml --cov-report=term-missing"

      # Copy coverage.xml from container to host
      - name: Copy coverage.xml
        run: docker cp my_app_test_container:/app/coverage.xml coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
